spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: r1
            uri: lb://conference-service
            predicates:
              - Path=/api/conferences/**
          - id: r2
            uri: lb://keynote-service
            predicates:
              - Path=/api/keynotes/**
server:
  port: 80
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/